site_name: deepee
nav:
  - Home: index.md
  - Examples: examples.md
theme:
  name: material
  palette:
    primary: black
    accent: light blue
  font:
    text: Fira Sans
    mono: Fira Code